---
name: PR-verify

on:
  pull_request:

env:
  GO_VERSION: 1.20.4

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify
        run: |
          make verify
